[project]
name = "speed-administrator"
authors = ["speed-admin-team"]
description = "A decentralized platform for tracking and validating high-performance metrics"
telemetry = false
requirements = []

[contracts.speed-validation]
path = "contracts/speed-validation.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
